In [1]:
import torch as T
import numpy as np

In [3]:
t = T.Tensor()
type(t)

torch.Tensor

In [4]:
print(T.dtype)
print(T.device)
print(T.layout)

<class 'torch.dtype'>
<class 'torch.device'>
<class 'torch.layout'>


In [5]:
t1 = T.Tensor([1, 2, 3])
t2 = T.Tensor([1, 2, 3])

In [6]:
t3 = t1 + t2
t3
t3.dtype

torch.float32

In [7]:
data = np.array([1,2,3])
data

array([1, 2, 3])

In [8]:
t1 = T.Tensor(data) # class constructor
t2 = T.tensor(data) # factory function
t3 = T.as_tensor(data) # factory function
t4 = T.from_numpy(data) # factory function

In [9]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [10]:
print(t1.dtype)
print(t2.dtype)
print(t3.dtype)
print(t4.dtype)
T.get_default_dtype()

torch.float32
torch.int64
torch.int64
torch.int64


torch.float32

In [11]:
data[0] = 0
data[1] = 0
data[2] = 0

In [12]:
print(t1)
print(t2)
print(t3)
print(t4)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([0, 0, 0])
tensor([0, 0, 0])


In [14]:
T.tensor(data, dtype=T.float64)

tensor([0., 0., 0.], dtype=torch.float64)

In [15]:
T.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [17]:
T.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [18]:
T.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [20]:
T.rand(3,4)

tensor([[9.8910e-01, 1.0778e-01, 9.4334e-01, 9.2532e-01],
        [7.7147e-01, 9.6428e-04, 4.6607e-01, 8.7528e-01],
        [4.0771e-01, 7.1153e-01, 2.6290e-01, 7.4572e-02]])

In [25]:
t = T.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=T.float64)
t.size()

torch.Size([3, 4])

In [26]:
len(t.shape)

2

In [27]:
T.tensor(t.shape).prod()

tensor(12)

In [29]:
t.numel()

12

In [30]:
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]], dtype=torch.float64)

In [31]:
print(t.reshape(1,12))
print(t.reshape(1,12).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]], dtype=torch.float64)
torch.Size([1, 12])


In [32]:
print(t.reshape(1,12).squeeze())
print(t.reshape(1,12).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.], dtype=torch.float64)
torch.Size([12])


In [34]:
print(t.reshape(1,12).squeeze().unsqueeze(dim=0))
print(t.reshape(1,12).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]], dtype=torch.float64)
torch.Size([1, 12])


In [35]:
def flatten(t):
    t = t.reshape(1,-1)
    t.squeeze()
    return t

In [36]:
flatten(t)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]], dtype=torch.float64)

In [37]:
t.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]], dtype=torch.float64)

In [38]:
t1 = T.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

t2 = T.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])

t3 = T.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

In [43]:
t = T.stack((t1,t2,t3))
print(t.shape)
print(t)

torch.Size([3, 4, 4])
tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])


In [44]:
t = t.reshape(3,1,4,4)
print(t.shape)
print(t)

torch.Size([3, 1, 4, 4])
tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])


In [45]:
t[0] # first image

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [46]:
t[0][0] # first color channel in first image

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [47]:
t[0][0][0] # first row of pixels of first color channel in first image

tensor([1, 1, 1, 1])

In [48]:
t[0][0][0][0] # first pixel value of first row of pixels of first color channel in first image

tensor(1)

In [49]:
t.flatten()

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [58]:
print(t.flatten(start_dim=0).shape)
print(t.flatten(start_dim=1).shape)
print(t.flatten(start_dim=2).shape)
print(t.flatten(start_dim=3).shape)

torch.Size([48])
torch.Size([3, 16])
torch.Size([3, 1, 16])
torch.Size([3, 1, 4, 4])


In [60]:
print(t.flatten(start_dim=0))
print(t.flatten(start_dim=1)) # use this
print(t.flatten(start_dim=2))
print(t.flatten(start_dim=3))

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])
tensor([[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

        [[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]],

        [[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]]])
tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])


In [63]:
t1 = T.tensor([
    [1,2],
    [3,4]
], dtype=T.float64)

t2 = T.tensor([
    [9,8],
    [7,6]
], dtype=T.float64)

In [64]:
t1 + t2

tensor([[10., 10.],
        [10., 10.]], dtype=torch.float64)

In [76]:
t = T.tensor([
    [0,5,7],
    [6,0,3],
    [0,8,0]
], dtype=T.float32)

In [77]:
t.eq(0)

tensor([[ True, False, False],
        [False,  True, False],
        [ True, False,  True]])

In [78]:
t.gt(0)

tensor([[False,  True,  True],
        [ True, False,  True],
        [False,  True, False]])

In [79]:
t.sum().numel() < t.numel()

True

In [80]:
t.sum(dim=0)

tensor([ 6., 13., 10.])

In [81]:
t.sum(dim=1)

tensor([12.,  9.,  8.])

In [82]:
t.max()

tensor(8.)

In [83]:
t.argmax()

tensor(7)

In [84]:
t.argmax(dim=0)

tensor([1, 2, 0])

In [85]:
t.max(dim=0)

torch.return_types.max(
values=tensor([6., 8., 7.]),
indices=tensor([1, 2, 0]))

In [86]:
t.argmax(dim=1)

tensor([2, 0, 1])

In [87]:
t.max(dim=1)

torch.return_types.max(
values=tensor([7., 6., 8.]),
indices=tensor([2, 0, 1]))

In [88]:
t.mean().item()

3.222222328186035

In [89]:
t.mean(dim=0).tolist()

[2.0, 4.333333492279053, 3.3333332538604736]