Stack Vs Concatination

In [1]:
import torch

In [6]:
t1 = torch.tensor([1,1,1])

t11 = t1.unsqueeze(dim=0)
t12 = t1.unsqueeze(dim=1)

print(t1.shape)
print(t11.shape)
print(t12.shape)

print(t1)
print(t11)
print(t12)

torch.Size([3])
torch.Size([1, 3])
torch.Size([3, 1])
tensor([1, 1, 1])
tensor([[1, 1, 1]])
tensor([[1],
        [1],
        [1]])


Concatination - joints a sequence of tensor along an existing axis,
Stacking - joins a sequence of tensors along a new axis

In [8]:
import torch

In [9]:
t1 = torch.tensor([1,1,1])
t2 = torch.tensor([2,2,2])
t3 = torch.tensor([3,3,3])

In [13]:
torch.cat(
    (t1,t2,t3)
    ,dim=0
)

tensor([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [15]:
torch.stack(
    (t1,t2,t3)
    ,dim=0
)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [16]:
torch.cat(
    (t1.unsqueeze(dim=0)
     ,t2.unsqueeze(dim=0)
     ,t3.unsqueeze(dim=0)
    )
    ,dim=0
)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [17]:
torch.stack(
    (t1,t2,t3)
    ,dim=1
)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [18]:
torch.cat(
    (t1.unsqueeze(dim=1)
     ,t2.unsqueeze(dim=1)
     ,t3.unsqueeze(dim=1)
    )
    ,dim=1
)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [19]:
import numpy as np

In [20]:
??np.stack

In [21]:
??torch.stack